version: "3"

services:
  sonarqube:
    image: sonarqube:9-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube9_data:/opt/sonarqube/data
      - sonarqube9_extensions:/opt/sonarqube/extensions
      - sonarqube9_logs:/opt/sonarqube/logs
      - sonarqube9_temp:/opt/sonarqube/temp
    ports:
      # NOTE: starting to see modern net proxies using port 9000; remap as needed.
      - "9900:9000"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql_13:/var/lib/postgresql
      - postgresql_13_data:/var/lib/postgresql/data

volumes:
  sonarqube9_data:
  sonarqube9_extensions:
  sonarqube9_logs:
  sonarqube9_temp:
  postgresql_13:
  postgresql_13_data:
